#!/usr/bin/env bash
#  batterybar; displays battery percentage as a bar on i3blocks
#  
#  Copyright 2015 Keftaa <adnan.37h@gmail.com>
#  
#  This program is free software; you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation; either version 2 of the License, or
#  (at your option) any later version.
#  
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with this program; if not, write to the Free Software
#  Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
#  MA 02110-1301, USA.
#  
#  

percentage=$(acpi | grep -Eo "[0-9]+%" | tr -d '%')

function bar {
    CHAR='█'

    ACTUAL=$1
    MAX=$2
    for i in `seq $2`; do

        if [ ${i} -lt $(awk "BEGIN {print int($MAX/100*$ACTUAL)}") ]; then
            printf "▇"
        else
            printf "▁"
        fi
    done
}

echo $(bar $percentage 10)
